[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Dwait Pandhi <dwait.pandhi@gmail.com> Isaac Sun <isaacsuh12@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "pymongo>=4.13.2",
    "python-dotenv>=1.1.0",
]
